### ISSUE TITLE
but how can you custom you row 

### ISSUE THREAD

**Issue by ManBali** [rameshvishnoi90904/react-native-recycler-listview#2]

**Comment by ManBali** [comment]
but how can you custom you row view. 
i had seen you bind the native attitude, but if i want to re design the row view by modify the js code ,then push the code to the code push platform ,can i do like this ? thanks very much

**Comment by rameshvishnoi90904** [comment]
@wsf5918 i have passed js array as props to native module and used this list to create list of ListViewCell which is then used as individual row in RecyclerView. If you checkout customAdaptor class for Recycler Listview i have inflated movie_list_row layout for rendering rows. so you have to design/modify movie_list_row layout for your application
